# Shell variables
# Generated by 'wal'
wallpaper='/home/mag/Pictures/wp2301621-anime-4k-wallpapers.jpg'

# Special
background='#050614'
foreground='#c8cecc'
cursor='#c8cecc'

# Colors
color0='#050614'
color1='#525365'
color2='#988762'
color3='#33608E'
color4='#50709E'
color5='#5E8AB1'
color6='#67A0C6'
color7='#c8cecc'
color8='#8c908e'
color9='#525365'
color10='#988762'
color11='#33608E'
color12='#50709E'
color13='#5E8AB1'
color14='#67A0C6'
color15='#c8cecc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
