--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mag/.config/wpg/wallpapers/wp2301613-anime-4k-wallpapers.jpg"

-- Special
background="#120c13"
foreground="#f2e2c7"
cursor="#f2e2c7"

-- Colors
color0="#120c13"
color1="#A55165"
color2="#D46956"
color3="#EF9F5C"
color4="#F2AF5A"
color5="#8E5487"
color6="#F0B38B"
color7="#f2e2c7"
color8="#a99e8b"
color9="#A55165"
color10="#D46956"
color11="#EF9F5C"
color12="#F2AF5A"
color13="#8E5487"
color14="#F0B38B"
color15="#f2e2c7"
