# Shell variables
# Generated by 'wal'
wallpaper='/home/mag/Pictures/mt-celeste-peak.png'

# Special
background='#3d2744'
foreground='#f3e0f2'
cursor='#f3e0f2'

# Colors
color0='#3d2744'
color1='#7C89C0'
color2='#AA83B8'
color3='#EE95D2'
color4='#F6ADD8'
color5='#E8A3E7'
color6='#FBCDDB'
color7='#f3e0f2'
color8='#aa9ca9'
color9='#7C89C0'
color10='#AA83B8'
color11='#EE95D2'
color12='#F6ADD8'
color13='#E8A3E7'
color14='#FBCDDB'
color15='#f3e0f2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
