--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mag/Pictures/madeline.jpg"

-- Special
background="#1e1c1c"
foreground="#cdd1da"
cursor="#cdd1da"

-- Colors
color0="#1e1c1c"
color1="#6577A1"
color2="#6F83AA"
color3="#9F8EA4"
color4="#E0A193"
color5="#FBDF9A"
color6="#FEF08B"
color7="#cdd1da"
color8="#8f9298"
color9="#6577A1"
color10="#6F83AA"
color11="#9F8EA4"
color12="#E0A193"
color13="#FBDF9A"
color14="#FEF08B"
color15="#cdd1da"
