--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mag/.utils/wallpapers/wi92248710f50-2462-4e80-8e6a-5b4847f0bd9a43688189.png"

-- Special
background="#0A0F15"
foreground="#f6e1c7"
cursor="#f6e1c7"

-- Colors
color0="#0A0F15"
color1="#AF5458"
color2="#F79567"
color3="#746A87"
color4="#A1788E"
color5="#AE8DA5"
color6="#E0A3A2"
color7="#f6e1c7"
color8="#ac9d8b"
color9="#AF5458"
color10="#F79567"
color11="#746A87"
color12="#A1788E"
color13="#AE8DA5"
color14="#E0A3A2"
color15="#f6e1c7"
