# Shell variables
# Generated by 'wal'
wallpaper='/home/mag/Downloads/complete-1.png'

# Special
background='#090A1B'
foreground='#e3e7e8'
cursor='#e3e7e8'

# Colors
color0='#090A1B'
color1='#F7B54F'
color2='#335C8A'
color3='#616097'
color4='#A77689'
color5='#6D8EB1'
color6='#AAAEC2'
color7='#e3e7e8'
color8='#9ea1a2'
color9='#F7B54F'
color10='#335C8A'
color11='#616097'
color12='#A77689'
color13='#6D8EB1'
color14='#AAAEC2'
color15='#e3e7e8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
