#!/bin/sh

#sxhkd startup
if [[ $(pgrep -x sxhkd) ]]; then 
	pkill -x sxhkd;
	sxhkd;
fi

bspc rule -r "*"

# AutoStart
picom &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
wmname compiz &
if [[ $(pgrep -x clipit) ]]; then 
	pkill -x clipit;
	clipit; 
fi
xfce4-panel -d &
lxsession &
flameshot &
nm-applet &
/usr/bin/python3 /usr/bin/touchpad-indicator &
blueman-applet &
dunst &

# Configure
	bspc monitor eDP-1 -d 1 2 3 4 5 &
	bspc monitor eDP-1 -d 1 2 3 4 5 &
	bspc config focused_border_color $(xrdb -get "color3") &
	bspc config normal_border_color $(xrdb -get "color0") &
	#bspc config active_border_color #CF0707
	#bspc config click_to_focus button1 &
	bspc config focus_follows_pointer true &
	bspc config swallow_first_click false &
	bspc config split_ratio 0.5 &
	bspc config pointer_modifier super &
	bspc config pointer_action1 move &
	bspc config pointer_action3 resize_corner &
	bspc config top_padding 35 &
	bspc config right_padding -4 &
	bspc config left_padding -4 &
	bspc config bottom_padding -4 &
	bspc config border_width 4
	bspc config window_gap 15 &

#Rules
	bspc rule -a "Wrapper-2.0" state=floating &
	bspc rule -a "Zathura" state=tiled &
#	bspc rule -a "focused.[!]focused" border=off &
#	bspc rule -a "Xfce4-panel" focus=on
#	bspc rule -a "xfce4-panel" focus=on
