#!/bin/sh
bspc rule -r "*"
#sxhkd startup
if [[ $(pgrep -x sxhkd) ]]; then 
	pkill -x sxhkd;
fi
sxhkd &
# AutoStart
picom --animations --experimental-backends --animation-dampening 15 &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
wmname compiz &
if [[ $(pgrep -x clipit) ]]; then 
	pkill -x clipit; 
fi
clipit &
xfce4-panel -d &
lxsession &
flameshot &
nm-applet &
if [[ $(pgrep -x volumeicon) ]]; then 
	pkill -x volumeicon;
fi
volumeicon &
# /usr/bin/python3 /usr/bin/touchpad-indicator &
# blueman-applet &
if [[ $(pgrep -x dunst) ]]; then 
	pkill -x dunst;
fi
dunst &
.local/scripts/toggle_touchpad.sh -r &
thunar --daemon &

# Configure
	bspc monitor eDP-1 -d 1 2 3 4 5 &
	bspc monitor eDP-1 -d 1 2 3 4 5 &
	bspc config focused_border_color $(xrdb -get "color3") &
	bspc config normal_border_color $(xrdb -get "color0") &
	bspc config automatic_scheme alternate
	# bspc config active_border_color #CF0707
	# bspc config click_to_focus button1 &
	bspc config focus_follows_pointer true &
	bspc config swallow_first_click false &
	bspc config split_ratio 0.55 &
	bspc config pointer_modifier super &
	bspc config pointer_action1 move &
	bspc config pointer_action3 resize_corner &
	gap=10
	bspc config top_padding 39+$gap &
	padding=0
	bspc config right_padding $padding &
	bspc config left_padding $padding &
	bspc config bottom_padding $padding &
	bspc config border_width 4
	bspc config window_gap $gap &

#Rules
	bspc rule -a "Wrapper-2.0" state=floating &
	bspc rule -a "Zathura" state=tiled &
	# bspc rule -a "focused.[!]focused" border=off &
	# bspc rule -a "Xfce4-panel" focus=on
	# bspc rule -a "xfce4-panel" focus=ons
